apiVersion: v1
kind: Secret
metadata:
  name: serving-azure-secret
type: Opaque
data:
  azurestorageaccountname: "{{ .Values.azure_storage_account_name | b64enc }}"
  azurestorageaccountkey: "{{ .Values.azure_storage_account_key | b64enc }}"
